
package org.drip.execution.optimum;

/*
 * -*- mode: java; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 */

/*!
 * Copyright (C) 2017 Lakshmi Krishnamurthy
 * Copyright (C) 2016 Lakshmi Krishnamurthy
 * 
 *  This file is part of DRIP, a free-software/open-source library for buy/side financial/trading model
 *  	libraries targeting analysts and developers
 *  	https://lakshmidrip.github.io/DRIP/
 *  
 *  DRIP is composed of four main libraries:
 *  
 *  - DRIP Fixed Income - https://lakshmidrip.github.io/DRIP-Fixed-Income/
 *  - DRIP Asset Allocation - https://lakshmidrip.github.io/DRIP-Asset-Allocation/
 *  - DRIP Numerical Optimizer - https://lakshmidrip.github.io/DRIP-Numerical-Optimizer/
 *  - DRIP Statistical Learning - https://lakshmidrip.github.io/DRIP-Statistical-Learning/
 * 
 *  - DRIP Fixed Income: Library for Instrument/Trading Conventions, Treasury Futures/Options,
 *  	Funding/Forward/Overnight Curves, Multi-Curve Construction/Valuation, Collateral Valuation and XVA
 *  	Metric Generation, Calibration and Hedge Attributions, Statistical Curve Construction, Bond RV
 *  	Metrics, Stochastic Evolution and Option Pricing, Interest Rate Dynamics and Option Pricing, LMM
 *  	Extensions/Calibrations/Greeks, Algorithmic Differentiation, and Asset Backed Models and Analytics.
 * 
 *  - DRIP Asset Allocation: Library for model libraries for MPT framework, Black Litterman Strategy
 *  	Incorporator, Holdings Constraint, and Transaction Costs.
 * 
 *  - DRIP Numerical Optimizer: Library for Numerical Optimization and Spline Functionality.
 * 
 *  - DRIP Statistical Learning: Library for Statistical Evaluation and Machine Learning.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *   	you may not use this file except in compliance with the License.
 *   
 *  You may obtain a copy of the License at
 *  	http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing, software
 *  	distributed under the License is distributed on an "AS IS" BASIS,
 *  	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  
 *  See the License for the specific language governing permissions and
 *  	limitations under the License.
 */

/**
 * EfficientTradingTrajectoryContinuous contains the Efficient Trading Trajectory generated by one of the
 *  Methods outlined in the Almgren (2003) Scheme for Continuous Trading Approximation. The References are:
 * 
 * 	- Almgren, R., and N. Chriss (1999): Value under Liquidation, Risk 12 (12).
 * 
 * 	- Almgren, R., and N. Chriss (2000): Optimal Execution of Portfolio Transactions, Journal of Risk 3 (2)
 * 		5-39.
 * 
 * 	- Almgren, R. (2003): Optimal Execution with Nonlinear Impact Functions and Trading-Enhanced Risk,
 * 		Applied Mathematical Finance 10 (1) 1-18.
 * 
 * 	- Almgren, R., and N. Chriss (2003): Bidding Principles, Risk 97-102.
 * 
 * 	- Bertsimas, D., and A. W. Lo (1998): Optimal Control of Execution Costs, Journal of Financial Markets,
 * 		1, 1-50.
 * 
 * @author Lakshmi Krishnamurthy
 */

public class EfficientTradingTrajectoryContinuous extends
	org.drip.execution.strategy.ContinuousTradingTrajectory implements
		org.drip.execution.optimum.EfficientTradingTrajectory {
	private double _dblMarketPower = java.lang.Double.NaN;
	private double _dblCharacteristicTime = java.lang.Double.NaN;
	private double _dblTransactionCostVariance = java.lang.Double.NaN;
	private double _dblTransactionCostExpectation = java.lang.Double.NaN;

	/**
	 * EfficientTradingTrajectoryContinuous Constructor
	 * 
	 * @param dblExecutionTime The Execution Time
	 * @param dblTransactionCostExpectation The Expected Transaction Cost
	 * @param dblTransactionCostVariance The Variance of the Transaction Cost
	 * @param dblCharacteristicTime The Optimal Trajectory's "Characteristic" Time
	 * @param dblMarketPower The Dimension-less Relative Market Impact
	 * @param r1ToR1Holdings The Optimal Trajectory R^1 To R^1 Holdings Function
	 * @param r1ToR1TradeRate The Optimal Trajectory R^1 To R^1 Trade Rate Function
	 * @param r1ToR1TransactionCostExpectation The Transaction Cost Expectation Function
	 * @param r1ToR1TransactionCostVariance The Transaction Cost Variance Function
	 * 
	 * @throws java.lang.Exception Thrown if the Inputs are Invalid
	 */

	public EfficientTradingTrajectoryContinuous (
		final double dblExecutionTime,
		final double dblTransactionCostExpectation,
		final double dblTransactionCostVariance,
		final double dblCharacteristicTime,
		final double dblMarketPower,
		final org.drip.function.definition.R1ToR1 r1ToR1Holdings,
		final org.drip.function.definition.R1ToR1 r1ToR1TradeRate,
		final org.drip.function.definition.R1ToR1 r1ToR1TransactionCostExpectation,
		final org.drip.function.definition.R1ToR1 r1ToR1TransactionCostVariance)
		throws java.lang.Exception
	{
		super (dblExecutionTime, r1ToR1Holdings, r1ToR1TradeRate, r1ToR1TransactionCostExpectation,
			r1ToR1TransactionCostVariance);

		if (!org.drip.quant.common.NumberUtil.IsValid (_dblTransactionCostExpectation =
			dblTransactionCostExpectation) || !org.drip.quant.common.NumberUtil.IsValid
				(_dblTransactionCostVariance = dblTransactionCostVariance) ||
					!org.drip.quant.common.NumberUtil.IsValid (_dblCharacteristicTime =
						dblCharacteristicTime))
			throw new java.lang.Exception
				("EfficientTradingTrajectoryContinuous Constructor => Invalid Inputs");
	}

	@Override public double marketPower()
	{
		return _dblMarketPower;
	}

	@Override public double transactionCostExpectation()
	{
		return _dblTransactionCostExpectation;
	}

	@Override public double transactionCostVariance()
	{
		return _dblTransactionCostVariance;
	}

	/**
	 * Retrieve the Optimal Trajectory Characteristic Time
	 * 
	 * @return The Optimal Trajectory Characteristic Time
	 */

	public double characteristicTime()
	{
		return _dblCharacteristicTime;
	}

	/**
	 * Retrieve the Optimal Trajectory Urgency
	 * 
	 * @return The Optimal Trajectory Urgency
	 */

	public double urgency()
	{
		return 0. == _dblCharacteristicTime ? 0. : 1. / _dblCharacteristicTime;
	}
}
